---
- hosts: all

  vars_files:
    - vars/brew.yml
    - vars/npm.yml

  tasks:
    - include: tasks/config.yml
      tags: config

    - include: tasks/brew.yml
      tags: brew

    - include: tasks/fonts.yml
      tags: fonts

    - include: tasks/npm.yml
      tags: npm
