---

- name: Install ngrok
  unarchive:
    copy: no
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
    dest: /usr/local/bin/
    creates: /usr/local/bin/ngrok

- name: Update ngrok to latest version
  command: ngrok update
